### ISSUE TITLE
No matching distribution found error for multiple modules

### ISSUE THREAD

**Issue by bitwisebro** [MrFlamez/spreddit#4]
when installing requirements.txt above error occurs for json and PIL! I didn't read src yet, but if its in built json, we don't need to install that and I think its Pillow instead of PIL!

**Comment by bitwisebro** [comment]
update: yes, json is inbuilt and its Pillow ! Creating PR!!

**Comment by MrFlamez** [comment]
thx for fixing. i wasnt sure if pil or pillow.

**Comment by bitwisebro** [comment]
Thanks! Closing this issue
